// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.example.tittle_tattle.algorithm.proto;

public interface ContactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.tittle_tattle.algorithm.proto.Contact)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 contacts = 1;</code>
   * @return The contacts.
   */
  int getContacts();

  /**
   * <code>int64 duration = 2;</code>
   * @return The duration.
   */
  long getDuration();

  /**
   * <code>int64 lastEncounterTime = 3;</code>
   * @return The lastEncounterTime.
   */
  long getLastEncounterTime();
}
