// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.example.tittle_tattle.algorithm.proto;

/**
 * Protobuf type {@code com.example.tittle_tattle.algorithm.proto.EncounteredNodes}
 */
public final class EncounteredNodes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.tittle_tattle.algorithm.proto.EncounteredNodes)
    EncounteredNodesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EncounteredNodes.newBuilder() to construct.
  private EncounteredNodes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EncounteredNodes() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EncounteredNodes();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EncounteredNodes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              encounters_ = com.google.protobuf.MapField.newMapField(
                  EncountersDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact>
            encounters__ = input.readMessage(
                EncountersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            encounters_.getMutableMap().put(
                encounters__.getKey(), encounters__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.tittle_tattle.algorithm.proto.HistoryOuterClass.internal_static_com_example_tittle_tattle_algorithm_proto_EncounteredNodes_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetEncounters();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.tittle_tattle.algorithm.proto.HistoryOuterClass.internal_static_com_example_tittle_tattle_algorithm_proto_EncounteredNodes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.tittle_tattle.algorithm.proto.EncounteredNodes.class, com.example.tittle_tattle.algorithm.proto.EncounteredNodes.Builder.class);
  }

  public static final int ENCOUNTERS_FIELD_NUMBER = 1;
  private static final class EncountersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact>newDefaultInstance(
                com.example.tittle_tattle.algorithm.proto.HistoryOuterClass.internal_static_com_example_tittle_tattle_algorithm_proto_EncounteredNodes_EncountersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.example.tittle_tattle.algorithm.proto.Contact.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> encounters_;
  private com.google.protobuf.MapField<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact>
  internalGetEncounters() {
    if (encounters_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          EncountersDefaultEntryHolder.defaultEntry);
    }
    return encounters_;
  }

  public int getEncountersCount() {
    return internalGetEncounters().getMap().size();
  }
  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
   */

  @java.lang.Override
  public boolean containsEncounters(
      long key) {
    
    return internalGetEncounters().getMap().containsKey(key);
  }
  /**
   * Use {@link #getEncountersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> getEncounters() {
    return getEncountersMap();
  }
  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> getEncountersMap() {
    return internalGetEncounters().getMap();
  }
  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
   */
  @java.lang.Override

  public com.example.tittle_tattle.algorithm.proto.Contact getEncountersOrDefault(
      long key,
      com.example.tittle_tattle.algorithm.proto.Contact defaultValue) {
    
    java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> map =
        internalGetEncounters().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
   */
  @java.lang.Override

  public com.example.tittle_tattle.algorithm.proto.Contact getEncountersOrThrow(
      long key) {
    
    java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> map =
        internalGetEncounters().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeLongMapTo(
        output,
        internalGetEncounters(),
        EncountersDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> entry
         : internalGetEncounters().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact>
      encounters__ = EncountersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, encounters__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.tittle_tattle.algorithm.proto.EncounteredNodes)) {
      return super.equals(obj);
    }
    com.example.tittle_tattle.algorithm.proto.EncounteredNodes other = (com.example.tittle_tattle.algorithm.proto.EncounteredNodes) obj;

    if (!internalGetEncounters().equals(
        other.internalGetEncounters())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetEncounters().getMap().isEmpty()) {
      hash = (37 * hash) + ENCOUNTERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetEncounters().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.tittle_tattle.algorithm.proto.EncounteredNodes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.tittle_tattle.algorithm.proto.EncounteredNodes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.tittle_tattle.algorithm.proto.EncounteredNodes)
      com.example.tittle_tattle.algorithm.proto.EncounteredNodesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tittle_tattle.algorithm.proto.HistoryOuterClass.internal_static_com_example_tittle_tattle_algorithm_proto_EncounteredNodes_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetEncounters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableEncounters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tittle_tattle.algorithm.proto.HistoryOuterClass.internal_static_com_example_tittle_tattle_algorithm_proto_EncounteredNodes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.tittle_tattle.algorithm.proto.EncounteredNodes.class, com.example.tittle_tattle.algorithm.proto.EncounteredNodes.Builder.class);
    }

    // Construct using com.example.tittle_tattle.algorithm.proto.EncounteredNodes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableEncounters().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.tittle_tattle.algorithm.proto.HistoryOuterClass.internal_static_com_example_tittle_tattle_algorithm_proto_EncounteredNodes_descriptor;
    }

    @java.lang.Override
    public com.example.tittle_tattle.algorithm.proto.EncounteredNodes getDefaultInstanceForType() {
      return com.example.tittle_tattle.algorithm.proto.EncounteredNodes.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.tittle_tattle.algorithm.proto.EncounteredNodes build() {
      com.example.tittle_tattle.algorithm.proto.EncounteredNodes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.tittle_tattle.algorithm.proto.EncounteredNodes buildPartial() {
      com.example.tittle_tattle.algorithm.proto.EncounteredNodes result = new com.example.tittle_tattle.algorithm.proto.EncounteredNodes(this);
      int from_bitField0_ = bitField0_;
      result.encounters_ = internalGetEncounters();
      result.encounters_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.tittle_tattle.algorithm.proto.EncounteredNodes) {
        return mergeFrom((com.example.tittle_tattle.algorithm.proto.EncounteredNodes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.tittle_tattle.algorithm.proto.EncounteredNodes other) {
      if (other == com.example.tittle_tattle.algorithm.proto.EncounteredNodes.getDefaultInstance()) return this;
      internalGetMutableEncounters().mergeFrom(
          other.internalGetEncounters());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.tittle_tattle.algorithm.proto.EncounteredNodes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.tittle_tattle.algorithm.proto.EncounteredNodes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> encounters_;
    private com.google.protobuf.MapField<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact>
    internalGetEncounters() {
      if (encounters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EncountersDefaultEntryHolder.defaultEntry);
      }
      return encounters_;
    }
    private com.google.protobuf.MapField<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact>
    internalGetMutableEncounters() {
      onChanged();;
      if (encounters_ == null) {
        encounters_ = com.google.protobuf.MapField.newMapField(
            EncountersDefaultEntryHolder.defaultEntry);
      }
      if (!encounters_.isMutable()) {
        encounters_ = encounters_.copy();
      }
      return encounters_;
    }

    public int getEncountersCount() {
      return internalGetEncounters().getMap().size();
    }
    /**
     * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
     */

    @java.lang.Override
    public boolean containsEncounters(
        long key) {
      
      return internalGetEncounters().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEncountersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> getEncounters() {
      return getEncountersMap();
    }
    /**
     * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> getEncountersMap() {
      return internalGetEncounters().getMap();
    }
    /**
     * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
     */
    @java.lang.Override

    public com.example.tittle_tattle.algorithm.proto.Contact getEncountersOrDefault(
        long key,
        com.example.tittle_tattle.algorithm.proto.Contact defaultValue) {
      
      java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> map =
          internalGetEncounters().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
     */
    @java.lang.Override

    public com.example.tittle_tattle.algorithm.proto.Contact getEncountersOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> map =
          internalGetEncounters().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearEncounters() {
      internalGetMutableEncounters().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
     */

    public Builder removeEncounters(
        long key) {
      
      internalGetMutableEncounters().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact>
    getMutableEncounters() {
      return internalGetMutableEncounters().getMutableMap();
    }
    /**
     * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
     */
    public Builder putEncounters(
        long key,
        com.example.tittle_tattle.algorithm.proto.Contact value) {
      
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableEncounters().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
     */

    public Builder putAllEncounters(
        java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact> values) {
      internalGetMutableEncounters().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.tittle_tattle.algorithm.proto.EncounteredNodes)
  }

  // @@protoc_insertion_point(class_scope:com.example.tittle_tattle.algorithm.proto.EncounteredNodes)
  private static final com.example.tittle_tattle.algorithm.proto.EncounteredNodes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.tittle_tattle.algorithm.proto.EncounteredNodes();
  }

  public static com.example.tittle_tattle.algorithm.proto.EncounteredNodes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EncounteredNodes>
      PARSER = new com.google.protobuf.AbstractParser<EncounteredNodes>() {
    @java.lang.Override
    public EncounteredNodes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EncounteredNodes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EncounteredNodes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EncounteredNodes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.tittle_tattle.algorithm.proto.EncounteredNodes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

