// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.example.tittle_tattle.algorithm.proto;

public interface EncounteredNodesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.tittle_tattle.algorithm.proto.EncounteredNodes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
   */
  int getEncountersCount();
  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
   */
  boolean containsEncounters(
      long key);
  /**
   * Use {@link #getEncountersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact>
  getEncounters();
  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
   */
  java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Contact>
  getEncountersMap();
  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
   */

  com.example.tittle_tattle.algorithm.proto.Contact getEncountersOrDefault(
      long key,
      com.example.tittle_tattle.algorithm.proto.Contact defaultValue);
  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Contact&gt; encounters = 1;</code>
   */

  com.example.tittle_tattle.algorithm.proto.Contact getEncountersOrThrow(
      long key);
}
