// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.example.tittle_tattle.algorithm.proto;

public interface EncounteredInterestsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.tittle_tattle.algorithm.proto.EncounteredInterests)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, int64&gt; interests = 1;</code>
   */
  int getInterestsCount();
  /**
   * <code>map&lt;int32, int64&gt; interests = 1;</code>
   */
  boolean containsInterests(
      int key);
  /**
   * Use {@link #getInterestsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Long>
  getInterests();
  /**
   * <code>map&lt;int32, int64&gt; interests = 1;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Long>
  getInterestsMap();
  /**
   * <code>map&lt;int32, int64&gt; interests = 1;</code>
   */

  long getInterestsOrDefault(
      int key,
      long defaultValue);
  /**
   * <code>map&lt;int32, int64&gt; interests = 1;</code>
   */

  long getInterestsOrThrow(
      int key);
}
