// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.example.tittle_tattle.algorithm.proto;

public interface HistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.tittle_tattle.algorithm.proto.History)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
   * @return Whether the socialNetwork field is set.
   */
  boolean hasSocialNetwork();
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
   * @return The socialNetwork.
   */
  com.example.tittle_tattle.algorithm.proto.SocialNetwork getSocialNetwork();
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
   */
  com.example.tittle_tattle.algorithm.proto.SocialNetworkOrBuilder getSocialNetworkOrBuilder();

  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
   * @return Whether the interests field is set.
   */
  boolean hasInterests();
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
   * @return The interests.
   */
  com.example.tittle_tattle.algorithm.proto.Interests getInterests();
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
   */
  com.example.tittle_tattle.algorithm.proto.InterestsOrBuilder getInterestsOrBuilder();

  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
   * @return Whether the encounteredNodes field is set.
   */
  boolean hasEncounteredNodes();
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
   * @return The encounteredNodes.
   */
  com.example.tittle_tattle.algorithm.proto.EncounteredNodes getEncounteredNodes();
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
   */
  com.example.tittle_tattle.algorithm.proto.EncounteredNodesOrBuilder getEncounteredNodesOrBuilder();
}
