// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.example.tittle_tattle.algorithm.proto;

/**
 * Protobuf type {@code com.example.tittle_tattle.algorithm.proto.History}
 */
public final class History extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.tittle_tattle.algorithm.proto.History)
    HistoryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use History.newBuilder() to construct.
  private History(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private History() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new History();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private History(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.example.tittle_tattle.algorithm.proto.SocialNetwork.Builder subBuilder = null;
            if (socialNetwork_ != null) {
              subBuilder = socialNetwork_.toBuilder();
            }
            socialNetwork_ = input.readMessage(com.example.tittle_tattle.algorithm.proto.SocialNetwork.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(socialNetwork_);
              socialNetwork_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.example.tittle_tattle.algorithm.proto.Interests.Builder subBuilder = null;
            if (interests_ != null) {
              subBuilder = interests_.toBuilder();
            }
            interests_ = input.readMessage(com.example.tittle_tattle.algorithm.proto.Interests.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(interests_);
              interests_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.example.tittle_tattle.algorithm.proto.EncounteredNodes.Builder subBuilder = null;
            if (encounteredNodes_ != null) {
              subBuilder = encounteredNodes_.toBuilder();
            }
            encounteredNodes_ = input.readMessage(com.example.tittle_tattle.algorithm.proto.EncounteredNodes.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(encounteredNodes_);
              encounteredNodes_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.tittle_tattle.algorithm.proto.HistoryOuterClass.internal_static_com_example_tittle_tattle_algorithm_proto_History_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.tittle_tattle.algorithm.proto.HistoryOuterClass.internal_static_com_example_tittle_tattle_algorithm_proto_History_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.tittle_tattle.algorithm.proto.History.class, com.example.tittle_tattle.algorithm.proto.History.Builder.class);
  }

  public static final int SOCIALNETWORK_FIELD_NUMBER = 1;
  private com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork_;
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
   * @return Whether the socialNetwork field is set.
   */
  @java.lang.Override
  public boolean hasSocialNetwork() {
    return socialNetwork_ != null;
  }
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
   * @return The socialNetwork.
   */
  @java.lang.Override
  public com.example.tittle_tattle.algorithm.proto.SocialNetwork getSocialNetwork() {
    return socialNetwork_ == null ? com.example.tittle_tattle.algorithm.proto.SocialNetwork.getDefaultInstance() : socialNetwork_;
  }
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
   */
  @java.lang.Override
  public com.example.tittle_tattle.algorithm.proto.SocialNetworkOrBuilder getSocialNetworkOrBuilder() {
    return getSocialNetwork();
  }

  public static final int INTERESTS_FIELD_NUMBER = 2;
  private com.example.tittle_tattle.algorithm.proto.Interests interests_;
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
   * @return Whether the interests field is set.
   */
  @java.lang.Override
  public boolean hasInterests() {
    return interests_ != null;
  }
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
   * @return The interests.
   */
  @java.lang.Override
  public com.example.tittle_tattle.algorithm.proto.Interests getInterests() {
    return interests_ == null ? com.example.tittle_tattle.algorithm.proto.Interests.getDefaultInstance() : interests_;
  }
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
   */
  @java.lang.Override
  public com.example.tittle_tattle.algorithm.proto.InterestsOrBuilder getInterestsOrBuilder() {
    return getInterests();
  }

  public static final int ENCOUNTEREDNODES_FIELD_NUMBER = 3;
  private com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes_;
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
   * @return Whether the encounteredNodes field is set.
   */
  @java.lang.Override
  public boolean hasEncounteredNodes() {
    return encounteredNodes_ != null;
  }
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
   * @return The encounteredNodes.
   */
  @java.lang.Override
  public com.example.tittle_tattle.algorithm.proto.EncounteredNodes getEncounteredNodes() {
    return encounteredNodes_ == null ? com.example.tittle_tattle.algorithm.proto.EncounteredNodes.getDefaultInstance() : encounteredNodes_;
  }
  /**
   * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
   */
  @java.lang.Override
  public com.example.tittle_tattle.algorithm.proto.EncounteredNodesOrBuilder getEncounteredNodesOrBuilder() {
    return getEncounteredNodes();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (socialNetwork_ != null) {
      output.writeMessage(1, getSocialNetwork());
    }
    if (interests_ != null) {
      output.writeMessage(2, getInterests());
    }
    if (encounteredNodes_ != null) {
      output.writeMessage(3, getEncounteredNodes());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (socialNetwork_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSocialNetwork());
    }
    if (interests_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInterests());
    }
    if (encounteredNodes_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getEncounteredNodes());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.tittle_tattle.algorithm.proto.History)) {
      return super.equals(obj);
    }
    com.example.tittle_tattle.algorithm.proto.History other = (com.example.tittle_tattle.algorithm.proto.History) obj;

    if (hasSocialNetwork() != other.hasSocialNetwork()) return false;
    if (hasSocialNetwork()) {
      if (!getSocialNetwork()
          .equals(other.getSocialNetwork())) return false;
    }
    if (hasInterests() != other.hasInterests()) return false;
    if (hasInterests()) {
      if (!getInterests()
          .equals(other.getInterests())) return false;
    }
    if (hasEncounteredNodes() != other.hasEncounteredNodes()) return false;
    if (hasEncounteredNodes()) {
      if (!getEncounteredNodes()
          .equals(other.getEncounteredNodes())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSocialNetwork()) {
      hash = (37 * hash) + SOCIALNETWORK_FIELD_NUMBER;
      hash = (53 * hash) + getSocialNetwork().hashCode();
    }
    if (hasInterests()) {
      hash = (37 * hash) + INTERESTS_FIELD_NUMBER;
      hash = (53 * hash) + getInterests().hashCode();
    }
    if (hasEncounteredNodes()) {
      hash = (37 * hash) + ENCOUNTEREDNODES_FIELD_NUMBER;
      hash = (53 * hash) + getEncounteredNodes().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.tittle_tattle.algorithm.proto.History parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tittle_tattle.algorithm.proto.History parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.History parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tittle_tattle.algorithm.proto.History parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.History parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tittle_tattle.algorithm.proto.History parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.History parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.tittle_tattle.algorithm.proto.History parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.History parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.tittle_tattle.algorithm.proto.History parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.History parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.tittle_tattle.algorithm.proto.History parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.tittle_tattle.algorithm.proto.History prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.tittle_tattle.algorithm.proto.History}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.tittle_tattle.algorithm.proto.History)
      com.example.tittle_tattle.algorithm.proto.HistoryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tittle_tattle.algorithm.proto.HistoryOuterClass.internal_static_com_example_tittle_tattle_algorithm_proto_History_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tittle_tattle.algorithm.proto.HistoryOuterClass.internal_static_com_example_tittle_tattle_algorithm_proto_History_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.tittle_tattle.algorithm.proto.History.class, com.example.tittle_tattle.algorithm.proto.History.Builder.class);
    }

    // Construct using com.example.tittle_tattle.algorithm.proto.History.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (socialNetworkBuilder_ == null) {
        socialNetwork_ = null;
      } else {
        socialNetwork_ = null;
        socialNetworkBuilder_ = null;
      }
      if (interestsBuilder_ == null) {
        interests_ = null;
      } else {
        interests_ = null;
        interestsBuilder_ = null;
      }
      if (encounteredNodesBuilder_ == null) {
        encounteredNodes_ = null;
      } else {
        encounteredNodes_ = null;
        encounteredNodesBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.tittle_tattle.algorithm.proto.HistoryOuterClass.internal_static_com_example_tittle_tattle_algorithm_proto_History_descriptor;
    }

    @java.lang.Override
    public com.example.tittle_tattle.algorithm.proto.History getDefaultInstanceForType() {
      return com.example.tittle_tattle.algorithm.proto.History.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.tittle_tattle.algorithm.proto.History build() {
      com.example.tittle_tattle.algorithm.proto.History result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.tittle_tattle.algorithm.proto.History buildPartial() {
      com.example.tittle_tattle.algorithm.proto.History result = new com.example.tittle_tattle.algorithm.proto.History(this);
      if (socialNetworkBuilder_ == null) {
        result.socialNetwork_ = socialNetwork_;
      } else {
        result.socialNetwork_ = socialNetworkBuilder_.build();
      }
      if (interestsBuilder_ == null) {
        result.interests_ = interests_;
      } else {
        result.interests_ = interestsBuilder_.build();
      }
      if (encounteredNodesBuilder_ == null) {
        result.encounteredNodes_ = encounteredNodes_;
      } else {
        result.encounteredNodes_ = encounteredNodesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.tittle_tattle.algorithm.proto.History) {
        return mergeFrom((com.example.tittle_tattle.algorithm.proto.History)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.tittle_tattle.algorithm.proto.History other) {
      if (other == com.example.tittle_tattle.algorithm.proto.History.getDefaultInstance()) return this;
      if (other.hasSocialNetwork()) {
        mergeSocialNetwork(other.getSocialNetwork());
      }
      if (other.hasInterests()) {
        mergeInterests(other.getInterests());
      }
      if (other.hasEncounteredNodes()) {
        mergeEncounteredNodes(other.getEncounteredNodes());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.tittle_tattle.algorithm.proto.History parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.tittle_tattle.algorithm.proto.History) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.tittle_tattle.algorithm.proto.SocialNetwork, com.example.tittle_tattle.algorithm.proto.SocialNetwork.Builder, com.example.tittle_tattle.algorithm.proto.SocialNetworkOrBuilder> socialNetworkBuilder_;
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
     * @return Whether the socialNetwork field is set.
     */
    public boolean hasSocialNetwork() {
      return socialNetworkBuilder_ != null || socialNetwork_ != null;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
     * @return The socialNetwork.
     */
    public com.example.tittle_tattle.algorithm.proto.SocialNetwork getSocialNetwork() {
      if (socialNetworkBuilder_ == null) {
        return socialNetwork_ == null ? com.example.tittle_tattle.algorithm.proto.SocialNetwork.getDefaultInstance() : socialNetwork_;
      } else {
        return socialNetworkBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
     */
    public Builder setSocialNetwork(com.example.tittle_tattle.algorithm.proto.SocialNetwork value) {
      if (socialNetworkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        socialNetwork_ = value;
        onChanged();
      } else {
        socialNetworkBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
     */
    public Builder setSocialNetwork(
        com.example.tittle_tattle.algorithm.proto.SocialNetwork.Builder builderForValue) {
      if (socialNetworkBuilder_ == null) {
        socialNetwork_ = builderForValue.build();
        onChanged();
      } else {
        socialNetworkBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
     */
    public Builder mergeSocialNetwork(com.example.tittle_tattle.algorithm.proto.SocialNetwork value) {
      if (socialNetworkBuilder_ == null) {
        if (socialNetwork_ != null) {
          socialNetwork_ =
            com.example.tittle_tattle.algorithm.proto.SocialNetwork.newBuilder(socialNetwork_).mergeFrom(value).buildPartial();
        } else {
          socialNetwork_ = value;
        }
        onChanged();
      } else {
        socialNetworkBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
     */
    public Builder clearSocialNetwork() {
      if (socialNetworkBuilder_ == null) {
        socialNetwork_ = null;
        onChanged();
      } else {
        socialNetwork_ = null;
        socialNetworkBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
     */
    public com.example.tittle_tattle.algorithm.proto.SocialNetwork.Builder getSocialNetworkBuilder() {
      
      onChanged();
      return getSocialNetworkFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
     */
    public com.example.tittle_tattle.algorithm.proto.SocialNetworkOrBuilder getSocialNetworkOrBuilder() {
      if (socialNetworkBuilder_ != null) {
        return socialNetworkBuilder_.getMessageOrBuilder();
      } else {
        return socialNetwork_ == null ?
            com.example.tittle_tattle.algorithm.proto.SocialNetwork.getDefaultInstance() : socialNetwork_;
      }
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.SocialNetwork socialNetwork = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.tittle_tattle.algorithm.proto.SocialNetwork, com.example.tittle_tattle.algorithm.proto.SocialNetwork.Builder, com.example.tittle_tattle.algorithm.proto.SocialNetworkOrBuilder> 
        getSocialNetworkFieldBuilder() {
      if (socialNetworkBuilder_ == null) {
        socialNetworkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.tittle_tattle.algorithm.proto.SocialNetwork, com.example.tittle_tattle.algorithm.proto.SocialNetwork.Builder, com.example.tittle_tattle.algorithm.proto.SocialNetworkOrBuilder>(
                getSocialNetwork(),
                getParentForChildren(),
                isClean());
        socialNetwork_ = null;
      }
      return socialNetworkBuilder_;
    }

    private com.example.tittle_tattle.algorithm.proto.Interests interests_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.tittle_tattle.algorithm.proto.Interests, com.example.tittle_tattle.algorithm.proto.Interests.Builder, com.example.tittle_tattle.algorithm.proto.InterestsOrBuilder> interestsBuilder_;
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
     * @return Whether the interests field is set.
     */
    public boolean hasInterests() {
      return interestsBuilder_ != null || interests_ != null;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
     * @return The interests.
     */
    public com.example.tittle_tattle.algorithm.proto.Interests getInterests() {
      if (interestsBuilder_ == null) {
        return interests_ == null ? com.example.tittle_tattle.algorithm.proto.Interests.getDefaultInstance() : interests_;
      } else {
        return interestsBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
     */
    public Builder setInterests(com.example.tittle_tattle.algorithm.proto.Interests value) {
      if (interestsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        interests_ = value;
        onChanged();
      } else {
        interestsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
     */
    public Builder setInterests(
        com.example.tittle_tattle.algorithm.proto.Interests.Builder builderForValue) {
      if (interestsBuilder_ == null) {
        interests_ = builderForValue.build();
        onChanged();
      } else {
        interestsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
     */
    public Builder mergeInterests(com.example.tittle_tattle.algorithm.proto.Interests value) {
      if (interestsBuilder_ == null) {
        if (interests_ != null) {
          interests_ =
            com.example.tittle_tattle.algorithm.proto.Interests.newBuilder(interests_).mergeFrom(value).buildPartial();
        } else {
          interests_ = value;
        }
        onChanged();
      } else {
        interestsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
     */
    public Builder clearInterests() {
      if (interestsBuilder_ == null) {
        interests_ = null;
        onChanged();
      } else {
        interests_ = null;
        interestsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
     */
    public com.example.tittle_tattle.algorithm.proto.Interests.Builder getInterestsBuilder() {
      
      onChanged();
      return getInterestsFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
     */
    public com.example.tittle_tattle.algorithm.proto.InterestsOrBuilder getInterestsOrBuilder() {
      if (interestsBuilder_ != null) {
        return interestsBuilder_.getMessageOrBuilder();
      } else {
        return interests_ == null ?
            com.example.tittle_tattle.algorithm.proto.Interests.getDefaultInstance() : interests_;
      }
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.Interests interests = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.tittle_tattle.algorithm.proto.Interests, com.example.tittle_tattle.algorithm.proto.Interests.Builder, com.example.tittle_tattle.algorithm.proto.InterestsOrBuilder> 
        getInterestsFieldBuilder() {
      if (interestsBuilder_ == null) {
        interestsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.tittle_tattle.algorithm.proto.Interests, com.example.tittle_tattle.algorithm.proto.Interests.Builder, com.example.tittle_tattle.algorithm.proto.InterestsOrBuilder>(
                getInterests(),
                getParentForChildren(),
                isClean());
        interests_ = null;
      }
      return interestsBuilder_;
    }

    private com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.tittle_tattle.algorithm.proto.EncounteredNodes, com.example.tittle_tattle.algorithm.proto.EncounteredNodes.Builder, com.example.tittle_tattle.algorithm.proto.EncounteredNodesOrBuilder> encounteredNodesBuilder_;
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
     * @return Whether the encounteredNodes field is set.
     */
    public boolean hasEncounteredNodes() {
      return encounteredNodesBuilder_ != null || encounteredNodes_ != null;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
     * @return The encounteredNodes.
     */
    public com.example.tittle_tattle.algorithm.proto.EncounteredNodes getEncounteredNodes() {
      if (encounteredNodesBuilder_ == null) {
        return encounteredNodes_ == null ? com.example.tittle_tattle.algorithm.proto.EncounteredNodes.getDefaultInstance() : encounteredNodes_;
      } else {
        return encounteredNodesBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
     */
    public Builder setEncounteredNodes(com.example.tittle_tattle.algorithm.proto.EncounteredNodes value) {
      if (encounteredNodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        encounteredNodes_ = value;
        onChanged();
      } else {
        encounteredNodesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
     */
    public Builder setEncounteredNodes(
        com.example.tittle_tattle.algorithm.proto.EncounteredNodes.Builder builderForValue) {
      if (encounteredNodesBuilder_ == null) {
        encounteredNodes_ = builderForValue.build();
        onChanged();
      } else {
        encounteredNodesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
     */
    public Builder mergeEncounteredNodes(com.example.tittle_tattle.algorithm.proto.EncounteredNodes value) {
      if (encounteredNodesBuilder_ == null) {
        if (encounteredNodes_ != null) {
          encounteredNodes_ =
            com.example.tittle_tattle.algorithm.proto.EncounteredNodes.newBuilder(encounteredNodes_).mergeFrom(value).buildPartial();
        } else {
          encounteredNodes_ = value;
        }
        onChanged();
      } else {
        encounteredNodesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
     */
    public Builder clearEncounteredNodes() {
      if (encounteredNodesBuilder_ == null) {
        encounteredNodes_ = null;
        onChanged();
      } else {
        encounteredNodes_ = null;
        encounteredNodesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
     */
    public com.example.tittle_tattle.algorithm.proto.EncounteredNodes.Builder getEncounteredNodesBuilder() {
      
      onChanged();
      return getEncounteredNodesFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
     */
    public com.example.tittle_tattle.algorithm.proto.EncounteredNodesOrBuilder getEncounteredNodesOrBuilder() {
      if (encounteredNodesBuilder_ != null) {
        return encounteredNodesBuilder_.getMessageOrBuilder();
      } else {
        return encounteredNodes_ == null ?
            com.example.tittle_tattle.algorithm.proto.EncounteredNodes.getDefaultInstance() : encounteredNodes_;
      }
    }
    /**
     * <code>.com.example.tittle_tattle.algorithm.proto.EncounteredNodes encounteredNodes = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.tittle_tattle.algorithm.proto.EncounteredNodes, com.example.tittle_tattle.algorithm.proto.EncounteredNodes.Builder, com.example.tittle_tattle.algorithm.proto.EncounteredNodesOrBuilder> 
        getEncounteredNodesFieldBuilder() {
      if (encounteredNodesBuilder_ == null) {
        encounteredNodesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.tittle_tattle.algorithm.proto.EncounteredNodes, com.example.tittle_tattle.algorithm.proto.EncounteredNodes.Builder, com.example.tittle_tattle.algorithm.proto.EncounteredNodesOrBuilder>(
                getEncounteredNodes(),
                getParentForChildren(),
                isClean());
        encounteredNodes_ = null;
      }
      return encounteredNodesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.tittle_tattle.algorithm.proto.History)
  }

  // @@protoc_insertion_point(class_scope:com.example.tittle_tattle.algorithm.proto.History)
  private static final com.example.tittle_tattle.algorithm.proto.History DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.tittle_tattle.algorithm.proto.History();
  }

  public static com.example.tittle_tattle.algorithm.proto.History getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<History>
      PARSER = new com.google.protobuf.AbstractParser<History>() {
    @java.lang.Override
    public History parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new History(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<History> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<History> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.tittle_tattle.algorithm.proto.History getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

