// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.example.tittle_tattle.algorithm.proto;

public interface InterestsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.tittle_tattle.algorithm.proto.Interests)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 interest = 1;</code>
   * @return A list containing the interest.
   */
  java.util.List<java.lang.Integer> getInterestList();
  /**
   * <code>repeated int32 interest = 1;</code>
   * @return The count of interest.
   */
  int getInterestCount();
  /**
   * <code>repeated int32 interest = 1;</code>
   * @param index The index of the element to return.
   * @return The interest at the given index.
   */
  int getInterest(int index);
}
