// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.example.tittle_tattle.algorithm.proto;

/**
 * Protobuf type {@code com.example.tittle_tattle.algorithm.proto.MessageExch}
 */
public final class MessageExch extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.tittle_tattle.algorithm.proto.MessageExch)
    MessageExchOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageExch.newBuilder() to construct.
  private MessageExch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageExch() {
    content_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageExch();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageExch(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            source_ = input.readInt64();
            break;
          }
          case 16: {

            timestamp_ = input.readInt64();
            break;
          }
          case 24: {

            topic1_ = input.readInt32();
            break;
          }
          case 32: {

            topic2_ = input.readInt32();
            break;
          }
          case 40: {

            topic3_ = input.readInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.tittle_tattle.algorithm.proto.Message.internal_static_com_example_tittle_tattle_algorithm_proto_MessageExch_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.tittle_tattle.algorithm.proto.Message.internal_static_com_example_tittle_tattle_algorithm_proto_MessageExch_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.tittle_tattle.algorithm.proto.MessageExch.class, com.example.tittle_tattle.algorithm.proto.MessageExch.Builder.class);
  }

  public static final int SOURCE_FIELD_NUMBER = 1;
  private long source_;
  /**
   * <code>int64 source = 1;</code>
   * @return The source.
   */
  @java.lang.Override
  public long getSource() {
    return source_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int TOPIC1_FIELD_NUMBER = 3;
  private int topic1_;
  /**
   * <code>int32 topic1 = 3;</code>
   * @return The topic1.
   */
  @java.lang.Override
  public int getTopic1() {
    return topic1_;
  }

  public static final int TOPIC2_FIELD_NUMBER = 4;
  private int topic2_;
  /**
   * <code>int32 topic2 = 4;</code>
   * @return The topic2.
   */
  @java.lang.Override
  public int getTopic2() {
    return topic2_;
  }

  public static final int TOPIC3_FIELD_NUMBER = 5;
  private int topic3_;
  /**
   * <code>int32 topic3 = 5;</code>
   * @return The topic3.
   */
  @java.lang.Override
  public int getTopic3() {
    return topic3_;
  }

  public static final int CONTENT_FIELD_NUMBER = 6;
  private volatile java.lang.Object content_;
  /**
   * <code>string content = 6;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 6;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (source_ != 0L) {
      output.writeInt64(1, source_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    if (topic1_ != 0) {
      output.writeInt32(3, topic1_);
    }
    if (topic2_ != 0) {
      output.writeInt32(4, topic2_);
    }
    if (topic3_ != 0) {
      output.writeInt32(5, topic3_);
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, content_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (source_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, source_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    if (topic1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, topic1_);
    }
    if (topic2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, topic2_);
    }
    if (topic3_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, topic3_);
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, content_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.tittle_tattle.algorithm.proto.MessageExch)) {
      return super.equals(obj);
    }
    com.example.tittle_tattle.algorithm.proto.MessageExch other = (com.example.tittle_tattle.algorithm.proto.MessageExch) obj;

    if (getSource()
        != other.getSource()) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getTopic1()
        != other.getTopic1()) return false;
    if (getTopic2()
        != other.getTopic2()) return false;
    if (getTopic3()
        != other.getTopic3()) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSource());
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + TOPIC1_FIELD_NUMBER;
    hash = (53 * hash) + getTopic1();
    hash = (37 * hash) + TOPIC2_FIELD_NUMBER;
    hash = (53 * hash) + getTopic2();
    hash = (37 * hash) + TOPIC3_FIELD_NUMBER;
    hash = (53 * hash) + getTopic3();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.tittle_tattle.algorithm.proto.MessageExch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tittle_tattle.algorithm.proto.MessageExch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.MessageExch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tittle_tattle.algorithm.proto.MessageExch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.MessageExch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tittle_tattle.algorithm.proto.MessageExch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.MessageExch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.tittle_tattle.algorithm.proto.MessageExch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.MessageExch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.tittle_tattle.algorithm.proto.MessageExch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.tittle_tattle.algorithm.proto.MessageExch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.tittle_tattle.algorithm.proto.MessageExch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.tittle_tattle.algorithm.proto.MessageExch prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.tittle_tattle.algorithm.proto.MessageExch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.tittle_tattle.algorithm.proto.MessageExch)
      com.example.tittle_tattle.algorithm.proto.MessageExchOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tittle_tattle.algorithm.proto.Message.internal_static_com_example_tittle_tattle_algorithm_proto_MessageExch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tittle_tattle.algorithm.proto.Message.internal_static_com_example_tittle_tattle_algorithm_proto_MessageExch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.tittle_tattle.algorithm.proto.MessageExch.class, com.example.tittle_tattle.algorithm.proto.MessageExch.Builder.class);
    }

    // Construct using com.example.tittle_tattle.algorithm.proto.MessageExch.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      source_ = 0L;

      timestamp_ = 0L;

      topic1_ = 0;

      topic2_ = 0;

      topic3_ = 0;

      content_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.tittle_tattle.algorithm.proto.Message.internal_static_com_example_tittle_tattle_algorithm_proto_MessageExch_descriptor;
    }

    @java.lang.Override
    public com.example.tittle_tattle.algorithm.proto.MessageExch getDefaultInstanceForType() {
      return com.example.tittle_tattle.algorithm.proto.MessageExch.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.tittle_tattle.algorithm.proto.MessageExch build() {
      com.example.tittle_tattle.algorithm.proto.MessageExch result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.tittle_tattle.algorithm.proto.MessageExch buildPartial() {
      com.example.tittle_tattle.algorithm.proto.MessageExch result = new com.example.tittle_tattle.algorithm.proto.MessageExch(this);
      result.source_ = source_;
      result.timestamp_ = timestamp_;
      result.topic1_ = topic1_;
      result.topic2_ = topic2_;
      result.topic3_ = topic3_;
      result.content_ = content_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.tittle_tattle.algorithm.proto.MessageExch) {
        return mergeFrom((com.example.tittle_tattle.algorithm.proto.MessageExch)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.tittle_tattle.algorithm.proto.MessageExch other) {
      if (other == com.example.tittle_tattle.algorithm.proto.MessageExch.getDefaultInstance()) return this;
      if (other.getSource() != 0L) {
        setSource(other.getSource());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getTopic1() != 0) {
        setTopic1(other.getTopic1());
      }
      if (other.getTopic2() != 0) {
        setTopic2(other.getTopic2());
      }
      if (other.getTopic3() != 0) {
        setTopic3(other.getTopic3());
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.tittle_tattle.algorithm.proto.MessageExch parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.tittle_tattle.algorithm.proto.MessageExch) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long source_ ;
    /**
     * <code>int64 source = 1;</code>
     * @return The source.
     */
    @java.lang.Override
    public long getSource() {
      return source_;
    }
    /**
     * <code>int64 source = 1;</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(long value) {
      
      source_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 source = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      
      source_ = 0L;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private int topic1_ ;
    /**
     * <code>int32 topic1 = 3;</code>
     * @return The topic1.
     */
    @java.lang.Override
    public int getTopic1() {
      return topic1_;
    }
    /**
     * <code>int32 topic1 = 3;</code>
     * @param value The topic1 to set.
     * @return This builder for chaining.
     */
    public Builder setTopic1(int value) {
      
      topic1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 topic1 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic1() {
      
      topic1_ = 0;
      onChanged();
      return this;
    }

    private int topic2_ ;
    /**
     * <code>int32 topic2 = 4;</code>
     * @return The topic2.
     */
    @java.lang.Override
    public int getTopic2() {
      return topic2_;
    }
    /**
     * <code>int32 topic2 = 4;</code>
     * @param value The topic2 to set.
     * @return This builder for chaining.
     */
    public Builder setTopic2(int value) {
      
      topic2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 topic2 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic2() {
      
      topic2_ = 0;
      onChanged();
      return this;
    }

    private int topic3_ ;
    /**
     * <code>int32 topic3 = 5;</code>
     * @return The topic3.
     */
    @java.lang.Override
    public int getTopic3() {
      return topic3_;
    }
    /**
     * <code>int32 topic3 = 5;</code>
     * @param value The topic3 to set.
     * @return This builder for chaining.
     */
    public Builder setTopic3(int value) {
      
      topic3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 topic3 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic3() {
      
      topic3_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 6;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 6;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 6;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <code>string content = 6;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.tittle_tattle.algorithm.proto.MessageExch)
  }

  // @@protoc_insertion_point(class_scope:com.example.tittle_tattle.algorithm.proto.MessageExch)
  private static final com.example.tittle_tattle.algorithm.proto.MessageExch DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.tittle_tattle.algorithm.proto.MessageExch();
  }

  public static com.example.tittle_tattle.algorithm.proto.MessageExch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageExch>
      PARSER = new com.google.protobuf.AbstractParser<MessageExch>() {
    @java.lang.Override
    public MessageExch parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageExch(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageExch> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageExch> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.tittle_tattle.algorithm.proto.MessageExch getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

