// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.example.tittle_tattle.algorithm.proto;

public interface MessageExchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.tittle_tattle.algorithm.proto.MessageExch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 source = 1;</code>
   * @return The source.
   */
  long getSource();

  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>int32 topic1 = 4;</code>
   * @return The topic1.
   */
  int getTopic1();

  /**
   * <code>int32 topic2 = 5;</code>
   * @return The topic2.
   */
  int getTopic2();

  /**
   * <code>int32 topic3 = 6;</code>
   * @return The topic3.
   */
  int getTopic3();
}
