// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.example.tittle_tattle.algorithm.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_tittle_tattle_algorithm_proto_MessageExch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_tittle_tattle_algorithm_proto_MessageExch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022)com.example.tittle_tatt" +
      "le.algorithm.proto\"q\n\013MessageExch\022\016\n\006sou" +
      "rce\030\001 \001(\003\022\021\n\ttimestamp\030\002 \001(\003\022\017\n\007content\030" +
      "\003 \001(\t\022\016\n\006topic1\030\004 \001(\005\022\016\n\006topic2\030\005 \001(\005\022\016\n" +
      "\006topic3\030\006 \001(\005B\004H\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_tittle_tattle_algorithm_proto_MessageExch_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_tittle_tattle_algorithm_proto_MessageExch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_tittle_tattle_algorithm_proto_MessageExch_descriptor,
        new java.lang.String[] { "Source", "Timestamp", "Content", "Topic1", "Topic2", "Topic3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
