// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.example.tittle_tattle.algorithm.proto;

public interface SocialNetworkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.tittle_tattle.algorithm.proto.SocialNetwork)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Interests&gt; node = 1;</code>
   */
  int getNodeCount();
  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Interests&gt; node = 1;</code>
   */
  boolean containsNode(
      long key);
  /**
   * Use {@link #getNodeMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Interests>
  getNode();
  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Interests&gt; node = 1;</code>
   */
  java.util.Map<java.lang.Long, com.example.tittle_tattle.algorithm.proto.Interests>
  getNodeMap();
  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Interests&gt; node = 1;</code>
   */

  com.example.tittle_tattle.algorithm.proto.Interests getNodeOrDefault(
      long key,
      com.example.tittle_tattle.algorithm.proto.Interests defaultValue);
  /**
   * <code>map&lt;int64, .com.example.tittle_tattle.algorithm.proto.Interests&gt; node = 1;</code>
   */

  com.example.tittle_tattle.algorithm.proto.Interests getNodeOrThrow(
      long key);
}
