// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history.proto

package com.example.tittle_tattle.algorithm.proto;

public interface SocialNetworkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.tittle_tattle.algorithm.proto.SocialNetwork)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 userId = 1;</code>
   * @return A list containing the userId.
   */
  java.util.List<java.lang.Long> getUserIdList();
  /**
   * <code>repeated int64 userId = 1;</code>
   * @return The count of userId.
   */
  int getUserIdCount();
  /**
   * <code>repeated int64 userId = 1;</code>
   * @param index The index of the element to return.
   * @return The userId at the given index.
   */
  long getUserId(int index);
}
